# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  lint-code:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
      - run:
          name: Lint code
          command: yarn lint:code

  lint-style:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
      - run:
          name: Lint style
          command: yarn lint:style

  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
      - run:
          name: Build (production)
          command: yarn build

workflows:
  verification:
    jobs:
      - lint-code
      - lint-style
      - build
