# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  setup-yarn:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          name: Restore cached lock file
          key: v2-yarn-lock-file-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --immutable
      - save_cache:
          name: Cache lock file.
          key: v2-yarn-lock-file-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache

  lint-code:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --immutable
      - run:
          name: Lint code
          command: yarn lint:code

  lint-style:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          name: Restore cached lock file
          key: v2-yarn-lock-file-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --immutable --immutable-cache
      - run:
          name: Lint style
          command: yarn lint:style

  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          name: Restore cached lock file
          key: v2-yarn-lock-file-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn install
          command: yarn install --immutable --immutable-cache
      - run:
          name: Build (production)
          command: yarn build

workflows:
  verification:
    jobs:
      - setup-yarn
      - lint-code:
          requires:
            - setup-yarn
      - lint-style:
          requires:
            - setup-yarn
      - build:
          requires:
            - setup-yarn
