name: Build and test

on: push

permissions: read-all

jobs:
  fixmes:
    name: FIXME check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: FIXME check
        uses: bbugh/action-fixme-check@v1.0.0
